camel:
  springboot:
    main-run-controller: true
    
logging:
  level:
    org.apache.camel: DEBUG

service:
  host: 0.0.0.0
  port: 8100

consul:
  host: docker.for.mac.localhost
  port: 8500
  
exposed:
  service: 
    name: Employee
  